### PR TITLE
Use system zip/unzip commands (if available)

### LINKED ISSUE #195: Make ext-zip optional
When running `pickle` in an enviroment without `ext-zip`, it fails early. This is for instance the case with the php binary that is bundled with macOS.

```
Fatal error: Uncaught Exception: Extension 'zip' required but not loaded, full required list: zlib, mbstring, simplexml, json, dom, openssl, phar, zip
```

To me, this seems like an unnecessary hard requirement. I recognize that on Windows, php extensions come precompiled and are distributed as ZIP files. But for other platforms, extensions are usually distributed as source tarballs.

Would it be possible to loosen that requirement a bit?

### PR DESCRIPTION
**Pull request by mlocati**
What about using the system `zip`/`unzip` commands (if available) instead of the `ZipArchive` class?

Fix #195

### CODE REVIEW

File: src/Console/Application.php [hunk 1]
```diff
@@ -52,13 +53,15 @@ private static function checkExtensions()
...
-            "zip",
         );
 
         foreach ($required_exts as $ext) {
             if (!extension_loaded($ext)) {
                 Throw new \Exception("Extension '$ext' required but not loaded, full required list: " . implode(", ", $required_exts));
             }
         }
+
+        Archive\Factory::getUnzipperClassName();
```
Comment (mlocati) [inline src/Console/Application.php:64]: We could also remove those two lines, and letting pickle fail later on, if the zip stuff is required (AFAIK when installing extensions under Windows, and when using the `release` command)

**Comment by pierrejoye** [comment]
Good morning,

Looks good and can be a bit more userfriendly. Also it will llmit composer usage (f.e. composer using zip archives from git), if I remember correctly.

Best,
